[[libsparseir]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3c94ef139569bfad3806064e55dab09d0a13f1c"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "96541d8733269f25233dacca6bee3ad05a4650fa44985a9b290b874c93144e93"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.aarch64-linux-gnu-cxx03.tar.gz"
[[libsparseir]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58a6a99ed0dd83250cc65e4d2f586f7e380a8bcb"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "15283dfe85585a47bfc19e118819a13cc958371872bbe692f93b7349ea9fc2eb"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[libsparseir]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5f6e0830e25a202d3d0f407e61343d28b84020e"
libc = "musl"
os = "linux"

    [[libsparseir.download]]
    sha256 = "f8620aecfeba8db77585a19e8b7f4d9b0725b7a2f960ddfdc6941ee5d4a3abb9"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.aarch64-linux-musl-cxx03.tar.gz"
[[libsparseir]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac4a6f304ce17ce3ae21d5dcf5dca234f2b65c45"
libc = "musl"
os = "linux"

    [[libsparseir.download]]
    sha256 = "dadf64037f984f0abc71a6f6c8d8391eaf61a3fd06c477481668151bf21a679a"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "97f4906d85e9b03f57782eae739c24aa7b56912a"
os = "freebsd"

    [[libsparseir.download]]
    sha256 = "36063acd5611328de5c04f0ffaac1dbe922cd751c68cdc02e91950fe8577e6da"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.aarch64-unknown-freebsd.tar.gz"
[[libsparseir]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa47b168ff4aeb92189f884e94a6d352a21533d0"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "0af4a00ca7214b01a4f585d3a3244bfb29ec11390cf9b03e13b067e300969d4c"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libsparseir]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86041d540efffb291a89b62a714b80483228399e"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "4cb8e9336e0e6d1ba6417096a5d0f8122eec8854b0dc2453dae5e34802e34800"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libsparseir]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69918196cd58d447fea69294bc43e73c67050480"
libc = "musl"
os = "linux"

    [[libsparseir.download]]
    sha256 = "16abf0fc930801a8bdc886ff362a1066c6672ba47928f8ef6c1e3ef4e0d7480f"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libsparseir]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "232776d4764c61e9a251047419bbc5d245d79c80"
libc = "musl"
os = "linux"

    [[libsparseir.download]]
    sha256 = "9198ced79a9beca52b1dc95a5bd820b540bc5afb9f794b4a95b7de42bf20004b"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libsparseir]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "976aeb29255d44056d9911ab2e15d9d74b011126"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "bd1125d84cfce2e45a8dd5f40c482c676e45ba7b2503065ad049d4e191d1fed4"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsparseir]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f39b00aff84a9b61678dad9bb432803d2e67f3dc"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "3dea12c14069bf65326dc022d4de79ce02923391d3c1a6b2fe84506181eecc41"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsparseir]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "253eab5f722aa265c4370c1ff0722540f1b8a1ec"
libc = "musl"
os = "linux"

    [[libsparseir.download]]
    sha256 = "07d033f12c90d02a2f7712d492aedc7a72d584bde74ec8f77eeb6ce027763704"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsparseir]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80700246c0797cdcf1fea9d8e6bbadccd1c12f61"
libc = "musl"
os = "linux"

    [[libsparseir.download]]
    sha256 = "04544e987af2519196eacb6c3562326577a01c02537636a71cff1f1f99398f2f"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsparseir]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "456db8d85dd1088ef72503d42e1797fe50049741"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "15f4b3079cc96247449f22363122fc65321b904a8f848b51b2f93611bf5a1d08"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.i686-linux-gnu-cxx03.tar.gz"
[[libsparseir]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b94024a7b6ee6589fbc5f2ed6141f481a26b067a"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "e53a999afefedf787e533d268462ba721dbce021e5f852105fd0fb5fd27ce037"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.i686-linux-gnu-cxx11.tar.gz"
[[libsparseir]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0835b4134f763ed29bf22c658825db91749207d3"
os = "windows"

    [[libsparseir.download]]
    sha256 = "0afa1f3f2f1ad94956821acce5a4731d66be408572cede677746dcbeba7faff3"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.i686-w64-mingw32-cxx03.tar.gz"
[[libsparseir]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ec58c25ba1a37e609f8846aabe58276a608ddd0"
os = "windows"

    [[libsparseir.download]]
    sha256 = "3d90785a81f6ba2a50b86a3cd580e2b6f760b0ee9f0a3cbb53c63d4b2bd53854"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.i686-w64-mingw32-cxx11.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "c616aecb706526c0697f15ed4489837f25a4998a"
os = "macos"

    [[libsparseir.download]]
    sha256 = "d902527a9ed09fd11d69fd6275004aba1e74b034564cdd3b43d49916e981387b"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.x86_64-apple-darwin.tar.gz"
[[libsparseir]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea2ab25980879b765d5989b738701bd07c35ef42"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "83f1094e2da08ff44d897403e81fc5a9ae23f72cb773e6fd77eeefd868cf0c85"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.x86_64-linux-gnu-cxx03.tar.gz"
[[libsparseir]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de6fd0befb313b6cc5d5a2f1a2fab0223717ac93"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "88ae974bc768b815ee16b7adfb932d59b781957604437f9c3c22a2ef5a649101"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[libsparseir]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db861a7fdf832acd28f83c236e7aaab31b9ba50e"
libc = "musl"
os = "linux"

    [[libsparseir.download]]
    sha256 = "c4c0a656b8eb17a0df5bf21ee7cba7dcbe18a375cbeb61ef8f8fdfd5912105cf"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.x86_64-linux-musl-cxx03.tar.gz"
[[libsparseir]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be1de950f53d802cb2ca590f5f644d14cb63e657"
libc = "musl"
os = "linux"

    [[libsparseir.download]]
    sha256 = "c17a4e4d11f76687a7547ba9d90214fe31f7dcf6f9c3588e846ab991f8868b2b"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.x86_64-linux-musl-cxx11.tar.gz"
[[libsparseir]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7665b936dbd6289c437d8a90358d10dbf50289c6"
os = "windows"

    [[libsparseir.download]]
    sha256 = "cbec9068c22aef7740dc3c2e931d8528a5a075faef2719dd4a820be2e7cf495a"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[libsparseir]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c80c5a4aa0e99d8349cfd808dfeedbc8b3eda3b"
os = "windows"

    [[libsparseir.download]]
    sha256 = "016feadede4ae8db5b9949acdd66b0b1fd9a01b0a6b41054e2fa27e4c48eb2d6"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.4.2+0/libsparseir.v0.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "383201ad7e730f06a7455d8aef57d3a0ea9a3735"
os = "macos"

    [[libsparseir.download]]
    sha256 = "e3f96d63b33d4791a555678fe3811c97cf4780d4d0ff6ac6537951a0ad904330"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.aarch64-apple-darwin.tar.gz"
[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "5ffe74c1b8558fafd4991eeb2fe055837701c02d"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "1719c884162452637a60c9d55c030e1ce9860dfc8b4ee90b0631bc5d68cb456a"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.aarch64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "powerpc64le"
git-tree-sha1 = "d8ef44b057c00dccb28f765d8720067959c390bc"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "5467c95ad079cb725b273c86b405797f8b11a9e65a0c312b9eb93b44e0b44353"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.powerpc64le-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "4880becc85bd4e52b05f4e341a9869ead7fdef0f"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "582de33e770cc3324e3f95e2b194ff2fb00bbaf81221892d43ec8a9c8af546e8"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.x86_64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "afe19e9ee119120d07bd5271150f9f767dd2c21f"
os = "freebsd"

    [[libsparseir.download]]
    sha256 = "3c41ee8e5801bf6bc35240b75338ea79f4602e03394e5e4f7e5ff35bd0d8a449"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.x86_64-unknown-freebsd.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "e5f74d403ebea272ce50f2d8517c8883fc0359ba"
os = "windows"

    [[libsparseir.download]]
    sha256 = "1a5545ca0b6e9346c361caa9383199d244f419b19ea6c84ebe9b2e814e356b93"
    url = "https://github.com/terasakisatoshi/LibSparseIR_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.x86_64-w64-mingw32.tar.gz"
