name = "libsparseir_jll"
uuid = "e5bf0e3f-5e75-5bb8-9f3f-2c07620468a3"
version = "0.7.2+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
libblastrampoline_jll = "8e850b90-86db-534c-a0d3-1478176c7d93"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.2.0"
julia = "1.10"
libblastrampoline_jll = "5.4.0"
Libdl = "1"
Artifacts = "1"
